title                    : "프리코네 6성 개화 도우미 priconne-six-star-help.io"
name                     : "영약한 여우들"
description              : "공부용으로 만들어보는 프리코네 6성 개화 도우미 사이트"
url                      : "https://priconne-six-star-help.io"
